apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::449590191337:role/eksctl-eksctl-demo-nodegroup-ng-4-NodeInstanceRole-16XQZQ6QD44Y9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::449590191337:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-25T02:38:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "43571"
  uid: 9aa81e2d-69e2-4243-bd59-b907c9358aba
